using Spotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Spotify
{
    internal class Spotify
    {
        public List<Song> Songs { get; set; }
        public List<Artist> Artists { get; set; }
 
        public List<Genre> Genres { get; set; }

        public Accounts CurrentUser { get; set; }
        public List<Accounts> Account { get; set; }
        public Spotify()
        {
            Songs = new List<Song>
            {
                new Song("Taylor Swift", "Shake It Off", "Pop"),
                new Song("Queen", "Bohemian Rhapsody", "Rock"),
                new Song("Kendrick Lamar", "HUMBLE.", "Hip-Hop"),
                new Song("Johnny Cash", "Ring of Fire", "Country"),
                new Song("Beyoncé", "Crazy in Love", "R&B"),
                new Song("Daft Punk", "Get Lucky", "Electronic"),
                new Song("Miles Davis", "So What", "Jazz"),
                new Song("Ludwig van Beethoven", "Symphony No. 5", "Classical"),
                new Song("Ariana Grande", "Thank U, Next", "Pop"),
                new Song("Led Zeppelin", "Stairway to Heaven", "Rock"),
                new Song("Drake", "God's Plan", "Hip-Hop"),
                new Song("Dolly Parton", "Jolene", "Country"),
                new Song("The Weeknd", "Blinding Lights", "R&B"),
                new Song("Calvin Harris", "Summer", "Electronic"),
                new Song("John Coltrane", "Giant Steps", "Jazz"),
                new Song("Wolfgang Amadeus Mozart", "Eine kleine Nachtmusik", "Classical"),
                new Song("Ed Sheeran", "Shape of You", "Pop"),
                new Song("The Rolling Stones", "Paint It Black", "Rock"),
                new Song("J. Cole", "No Role Modelz", "Hip-Hop"),
                new Song("Garth Brooks", "Friends in Low Places", "Country"),
                new Song("Alicia Keys", "Fallin'", "R&B"),
                new Song("Marshmello", "Happier", "Electronic"),
                new Song("Herbie Hancock", "Cantaloupe Island", "Jazz"),
                new Song("Johann Sebastian Bach", "Toccata and Fugue in D minor", "Classical"),
                new Song("Justin Bieber", "Sorry", "Pop"),
                new Song("Pink Floyd", "Wish You Were Here", "Rock"),
                new Song("Kanye West", "Stronger", "Hip-Hop"),
                new Song("Carrie Underwood", "Before He Cheats", "Country"),
                new Song("Usher", "Yeah!", "R&B"),
                new Song("Zedd", "Clarity", "Electronic"),
                new Song("Duke Ellington", "Take the 'A' Train", "Jazz"),
                new Song("Antonio Vivaldi", "The Four Seasons", "Classical"),
                new Song("Billie Eilish", "Bad Guy", "Pop"),
                new Song("Nirvana", "Smells Like Teen Spirit", "Rock"),
                new Song("Eminem", "Lose Yourself", "Hip-Hop"),
                new Song("Luke Bryan", "Country Girl (Shake It for Me)", "Country"),
                new Song("Marvin Gaye", "Let's Get It On", "R&B"),
                new Song("Skrillex", "Bangarang", "Electronic"),
                new Song("Louis Armstrong", "What a Wonderful World", "Jazz"),
                new Song("Frédéric Chopin", "Nocturne in E-flat major, Op. 9, No. 2", "Classical"),
                new Song("Katy Perry", "Roar", "Pop"),
                new Song("AC/DC", "Back in Black", "Rock"),
                new Song("Nicki Minaj", "Super Bass", "Hip-Hop"),
                new Song("Blake Shelton", "God's Country", "Country"),
                new Song("Whitney Houston", "I Will Always Love You", "R&B"),
                new Song("David Guetta", "Titanium", "Electronic"),
                new Song("Charlie Parker", "Ornithology", "Jazz"),
                new Song("Ludwig van Beethoven", "Fur Elise", "Classical"),
                new Song("Lady Gaga", "Poker Face", "Pop"),
                new Song("The Beatles", "Hey Jude", "Rock"),
                new Song("Cardi B", "Bodak Yellow", "Hip-Hop"),
                new Song("Miranda Lambert", "The House That Built Me", "Country"),
                new Song("Rihanna", "Umbrella", "R&B"),
                new Song("Avicii", "Wake Me Up", "Electronic"),
                new Song("Miles Davis", "Freddie Freeloader", "Jazz"),
                new Song("Pyotr Ilyich Tchaikovsky", "Swan Lake", "Classical"),
                new Song("Dua Lipa", "Don't Start Now", "Pop"),
                new Song("The Who", "Baba O'Riley", "Rock"),
                new Song("Travis Scott", "SICKO MODE", "Hip-Hop"),
                new Song("Chris Stapleton", "Tennessee Whiskey", "Country"),
                new Song("Mary J. Blige", "Family Affair", "R&B"),
                new Song("The Chainsmokers", "Closer", "Electronic"),
                new Song("John Coltrane", "My Favorite Things", "Jazz"),
                new Song("Johannes Brahms", "Hungarian Dance No. 5", "Classical"),
                new Song("Selena Gomez", "Lose You to Love Me", "Pop"),
                new Song("Aerosmith", "Dream On", "Rock"),
                new Song("Lil Nas X", "Old Town Road", "Hip-Hop"),
                new Song("Keith Urban", "Blue Ain't Your Color", "Country"),
                new Song("TLC", "No Scrubs", "R&B"),
                new Song("Kygo", "Firestone", "Electronic"),
                new Song("Chet Baker", "My Funny Valentine", "Jazz"),
                new Song("Franz Schubert", "Ave Maria", "Classical"),
                new Song("Shawn Mendes", "Stitches", "Pop"),
                new Song("Metallica", "Enter Sandman", "Rock"),
                new Song("Future", "Mask Off", "Hip-Hop"),
                new Song("Tim McGraw", "Humble and Kind", "Country"),
                new Song("Chris Brown", "Forever", "R&B"),
                new Song("Martin Garrix", "Animals", "Electronic"),
                new Song("Billie Holiday", "Summertime", "Jazz"),
                new Song("Claude Debussy", "Clair de Lune", "Classical"),
                new Song("Adele", "Hello", "Pop"),
                new Song("Red Hot Chili Peppers", "Californication", "Rock"),
                new Song("Post Malone", "Rockstar", "Hip-Hop"),
                new Song("Kacey Musgraves", "Follow Your Arrow", "Country"),
                new Song("Bruno Mars", "Just the Way You Are", "R&B"),
                new Song("Deadmau5", "Ghosts 'n' Stuff", "Electronic"),
                new Song("Dizzy Gillespie", "Salt Peanuts", "Jazz"),
                new Song("Richard Wagner", "Ride of the Valkyries", "Classical"),
                new Song("Maroon 5", "Sugar", "Pop"),
                new Song("Foo Fighters", "Everlong", "Rock"),
                new Song("Migos", "Bad and Boujee", "Hip-Hop"),
                new Song("Florida Georgia Line", "Cruise", "Country"),
                new Song("Ne-Yo", "Miss Independent", "R&B"),
                new Song("Steve Aoki", "Delirious", "Electronic"),
                new Song("Thelonious Monk", "Round Midnight", "Jazz"),
                new Song("Edvard Grieg", "In the Hall of the Mountain King", "Classical"),
                new Song("Britney Spears", "Toxic", "Pop"),
                new Song("Linkin Park", "In the End", "Rock"),
                new Song("Jay-Z", "Empire State of Mind", "Hip-Hop"),
                new Song("Brad Paisley", "Whiskey Lullaby", "Country"),
                new Song("Janet Jackson", "Rhythm Nation", "R&B"),
                new Song("Tiesto", "Red Lights", "Electronic"),
                new Song("Stan Getz", "The Girl from Ipanema", "Jazz"),
                new Song("Gustav Holst", "The Planets", "Classical"),
                new Song("Justin Timberlake", "Can't Stop the Feeling!", "Pop"),
                new Song("The Doors", "Light My Fire", "Rock"),
                new Song("Mac Miller", "Self Care", "Hip-Hop"),
                new Song("Shania Twain", "Man! I Feel Like a Woman!", "Country"),
                new Song("Sade", "Smooth Operator", "R&B"),
                new Song("Porter Robinson", "Shelter", "Electronic"),
                new Song("Ella Fitzgerald", "Dream a Little Dream of Me", "Jazz"),
                new Song("Camille Saint-Saëns", "Danse Macabre", "Classical"),
                new Song("One Direction", "What Makes You Beautiful", "Pop"),
                new Song("Jimi Hendrix", "Purple Haze", "Rock"),
                new Song("Juice WRLD", "Lucid Dreams", "Hip-Hop"),
                new Song("Jason Aldean", "Dirt Road Anthem", "Country"),
                new Song("Bobby Brown", "Every Little Step", "R&B"),
                new Song("Avicii", "Levels", "Electronic"),
                new Song("Miles Davis", "All Blues", "Jazz"),
                new Song("George Frideric Handel", "Messiah", "Classical"),
                new Song("Kesha", "Tik Tok", "Pop"),
                new Song("The Clash", "London Calling", "Rock"),
                new Song("A$AP Rocky", "Praise The Lord (Da Shine)", "Hip-Hop"),
                new Song("Eric Church", "Springsteen", "Country"),
                new Song("Anita Baker", "Sweet Love", "R&B"),
                new Song("Flume", "Never Be Like You", "Electronic"),
                new Song("Sonny Rollins", "St. Thomas", "Jazz"),
                new Song("Maurice Ravel", "Boléro", "Classical"),
                new Song("Rihanna", "Diamonds", "Pop"),
                new Song("Guns N' Roses", "Sweet Child O' Mine", "Rock"),
                new Song("Tyler, the Creator", "EARFQUAKE", "Hip-Hop"),
                new Song("Faith Hill", "Breathe", "Country"),
                new Song("Luther Vandross", "Never Too Much", "R&B"),
                new Song("Justice", "D.A.N.C.E.", "Electronic"),
                new Song("Django Reinhardt", "Minor Swing", "Jazz"),
                new Song("Igor Stravinsky", "The Rite of Spring", "Classical"),
                new Song("Selena Gomez", "Rare", "Pop"),
                new Song("David Bowie", "Heroes", "Rock"),
                new Song("Meek Mill", "Dreams and Nightmares", "Hip-Hop"),
                new Song("Trisha Yearwood", "She's in Love with the Boy", "Country"),
                new Song("Sam Cooke", "A Change Is Gonna Come", "R&B"),
                new Song("Kygo", "Stole the Show", "Electronic"),
                new Song("Art Blakey", "Moanin'", "Jazz"),
                new Song("Sergei Rachmaninoff", "Piano Concerto No. 2", "Classical"),
                new Song("Ariana Grande", "7 rings", "Pop"),
                new Song("Black Sabbath", "Paranoid", "Rock"),
                new Song("Lil Wayne", "A Milli", "Hip-Hop"),
                new Song("Kenny Chesney", "American Kids", "Country"),
                new Song("Marvin Gaye", "What's Going On", "R&B"),
                new Song("Major Lazer", "Lean On", "Electronic"),
                new Song("Charlie Parker", "Yardbird Suite", "Jazz"),
                new Song("Johann Strauss II", "The Blue Danube", "Classical"),
                new Song("Ed Sheeran", "Perfect", "Pop"),
                new Song("U2", "With or Without You", "Rock"),
                new Song("J. Cole", "Wet Dreamz", "Hip-Hop"),
                new Song("Darius Rucker", "Wagon Wheel", "Country"),
                new Song("Whitney Houston", "How Will I Know", "R&B"),
                new Song("Alesso", "Heroes (we could be)", "Electronic"),
                new Song("Herbie Hancock", "Watermelon Man", "Jazz"),
                new Song("Franz Liszt", "Hungarian Rhapsody No. 2", "Classical"),
                new Song("Britney Spears", "Oops!... I Did It Again", "Pop"),
                new Song("Bruce Springsteen", "Born to Run", "Rock"),
                new Song("Travis Scott", "goosebumps", "Hip-Hop"),
                new Song("Zac Brown Band", "Chicken Fried", "Country"),
                new Song("Otis Redding", "Sittin' On The Dock of the Bay", "R&B"),
                new Song("deadmau5", "Strobe", "Electronic"),
                new Song("Miles Davis", "Blue in Green", "Jazz"),
                new Song("Antonio Vivaldi", "Gloria", "Classical"),
                new Song("Lady Gaga", "Just Dance", "Pop"),
                new Song("Pearl Jam", "Alive", "Rock"),
                new Song("Drake", "In My Feelings", "Hip-Hop"),
                new Song("Dolly Parton", "9 to 5", "Country"),
                new Song("Erykah Badu", "On & On", "R&B"),
                new Song("Zedd", "Stay", "Electronic"),
                new Song("John Coltrane", "Naima", "Jazz"),
                new Song("Johann Sebastian Bach", "Brandenburg Concerto No. 3", "Classical"),
                new Song("Taylor Swift", "Blank Space", "Pop"),
                new Song("Led Zeppelin", "Whole Lotta Love", "Rock"),
                new Song("JAY-Z", "99 Problems", "Hip-Hop"),
                new Song("George Strait", "Amarillo by Morning", "Country"),
                new Song("Aretha Franklin", "Respect", "R&B"),
                new Song("Calvin Harris", "Feel So Close", "Electronic"),
                new Song("Ella Fitzgerald", "Blue Skies", "Jazz"),
                new Song("Wolfgang Amadeus Mozart", "Requiem", "Classical"),
                new Song("Justin Bieber", "Love Yourself", "Pop"),
                new Song("The Rolling Stones", "Gimme Shelter", "Rock"),
                new Song("OutKast", "Hey Ya!", "Hip-Hop"),
                new Song("Keith Urban", "Somebody Like You", "Country"),
                new Song("Tina Turner", "What's Love Got to Do with It", "R&B"),
                new Song("Skrillex", "Scary Monsters and Nice Sprites", "Electronic"),
                new Song("Miles Davis", "So What", "Jazz"),
                new Song("Frédéric Chopin", "Prelude in D-flat major, Op. 28, No. 15", "Classical"),
                new Song("Katy Perry", "Firework", "Pop"),
                new Song("AC/DC", "Highway to Hell", "Rock"),
                new Song("Lil Nas X", "Panini", "Hip-Hop"),
                new Song("Reba McEntire", "Fancy", "Country"),
                new Song("Toni Braxton", "Un-Break My Heart", "R&B"),
                new Song("Kygo", "It Ain't Me", "Electronic"),
                new Song("Billie Holiday", "God Bless the Child", "Jazz"),
                new Song("Ludwig van Beethoven", "Moonlight Sonata", "Classical"),
                new Song("Adele", "Rolling in the Deep", "Pop"),
                new Song("Queen", "We Will Rock You", "Rock"),
                new Song("Eminem", "Without Me", "Hip-Hop"),
                new Song("Shania Twain", "You're Still the One", "Country"),
                new Song("Sade", "By Your Side", "R&B"),
                new Song("David Guetta", "When Love Takes Over", "Electronic"),
                new Song("John Coltrane", "Blue Train", "Jazz"),
                new Song("Wolfgang Amadeus Mozart", "The Magic Flute", "Classical"),
                new Song("Britney Spears", "Circus", "Pop"),
                new Song("Metallica", "Nothing Else Matters", "Rock"),
                new Song("Drake", "Hotline Bling", "Hip-Hop"),
                new Song("Tim McGraw", "Live Like You Were Dying", "Country"),
                new Song("Mariah Carey", "Hero", "R&B"),
                new Song("Avicii", "The Nights", "Electronic"),
                new Song("Miles Davis", "Milestones", "Jazz"),
                new Song("Richard Strauss", "Also sprach Zarathustra", "Classical"),
                new Song("Selena Gomez", "Come & Get It", "Pop"),
                new Song("The Who", "My Generation", "Rock"),
                new Song("Post Malone", "Circles", "Hip-Hop"),
                new Song("Dierks Bentley", "Drunk on a Plane", "Country"),
                new Song("Beyoncé", "Irreplaceable", "R&B"),
                new Song("Calvin Harris", "I'm Not Alone", "Electronic"),
                new Song("Charlie Parker", "Confirmation", "Jazz"),
                new Song("Franz Schubert", "Symphony No. 8", "Classical"),
                new Song("Taylor Swift", "Love Story", "Pop"),
                new Song("The Beatles", "Come Together", "Rock"),
                new Song("Travis Scott", "HIGHEST IN THE ROOM", "Hip-Hop"),
                new Song("Garth Brooks", "The Dance", "Country"),
                new Song("Alicia Keys", "If I Ain't Got You", "R&B"),
                new Song("David Guetta", "Play Hard", "Electronic"),
                new Song("Herbie Hancock", "Maiden Voyage", "Jazz"),
                new Song("Ludwig van Beethoven", "Symphony No. 9", "Classical"),
                new Song("Lady Gaga", "Born This Way", "Pop"),
                new Song("Pink Floyd", "Another Brick in the Wall", "Rock"),
                new Song("Kendrick Lamar", "Alright", "Hip-Hop"),
                new Song("Carrie Underwood", "Jesus, Take the Wheel", "Country"),
                new Song("Usher", "U Got It Bad", "R&B"),
                new Song("Marshmello", "Alone", "Electronic"),
                new Song("John Coltrane", "Cousin Mary", "Jazz"),
                new Song("Pyotr Ilyich Tchaikovsky", "1812 Overture", "Classical"),
                new Song("Ed Sheeran", "Castle on the Hill", "Pop"),
                new Song("The Rolling Stones", "Sympathy for the Devil", "Rock"),
                new Song("J. Cole", "Middle Child", "Hip-Hop"),
                new Song("Luke Bryan", "Drunk on You", "Country"),
                new Song("Marvin Gaye", "Sexual Healing", "R&B"),
                new Song("Skrillex", "First of the Year (Equinox)", "Electronic"),
                new Song("Louis Armstrong", "La Vie En Rose", "Jazz"),
                new Song("Frédéric Chopin", "Polonaise in A-flat major, Op. 53", "Classical"),
                new Song("Justin Bieber", "Baby", "Pop"),
                new Song("Led Zeppelin", "Kashmir", "Rock"),
                new Song("Kanye West", "Gold Digger", "Hip-Hop"),
                new Song("Dolly Parton", "Islands in the Stream", "Country"),
                new Song("Mary J. Blige", "Real Love", "R&B"),
                new Song("The Chainsmokers", "Roses", "Electronic"),
                new Song("Duke Ellington", "Mood Indigo", "Jazz"),
                new Song("Antonio Vivaldi", "Concerto for Strings in G Major", "Classical"),
                new Song("Billie Eilish", "Ocean Eyes", "Pop"),
                new Song("Nirvana", "Come as You Are", "Rock"),
                new Song("Eminem", "Stan", "Hip-Hop"),
                new Song("Blake Shelton", "Honey Bee", "Country"),
                new Song("Whitney Houston", "I Wanna Dance with Somebody", "R&B"),
                new Song("Zedd", "The Middle", "Electronic"),
                new Song("Duke Ellington", "It Don't Mean a Thing (If It Ain't Got That Swing)", "Jazz"),
                new Song("Johann Sebastian Bach", "Air on the G String", "Classical"),
                new Song("Ariana Grande", "Break Free", "Pop"),
                new Song("Linkin Park", "Numb", "Rock"),
                new Song("Jay-Z", "Hard Knock Life (Ghetto Anthem)", "Hip-Hop"),
                new Song("Brad Paisley", "Mud on the Tires", "Country"),
                new Song("Janet Jackson", "All for You", "R&B"),
                new Song("Tiesto", "Wasted", "Electronic"),
                new Song("Stan Getz", "Desafinado", "Jazz"),
                new Song("Claude Debussy", "Prélude à l'après-midi d'un faune", "Classical"),
                new Song("Justin Timberlake", "SexyBack", "Pop"),
                new Song("The Doors", "People Are Strange", "Rock"),
                new Song("Mac Miller", "Good News", "Hip-Hop"),
                new Song("Shania Twain", "Any Man of Mine", "Country"),
                new Song("Sade", "No Ordinary Love", "R&B"),
                new Song("Porter Robinson", "Language", "Electronic"),
                new Song("Ella Fitzgerald", "Misty", "Jazz"),
                new Song("Camille Saint-Saëns", "The Carnival of the Animals", "Classical"),
                new Song("One Direction", "Story of My Life", "Pop"),
                new Song("Jimi Hendrix", "Hey Joe", "Rock"),
                new Song("Juice WRLD", "Wishing Well", "Hip-Hop"),
                new Song("Jason Aldean", "Big Green Tractor", "Country"),
                new Song("Bobby Brown", "My Prerogative", "R&B"),
                new Song("Avicii", "Hey Brother", "Electronic"),
                new Song("Miles Davis", "Flamenco Sketches", "Jazz"),
                new Song("George Frideric Handel", "Water Music", "Classical"),
                new Song("Kesha", "Praying", "Pop"),
                new Song("The Clash", "Should I Stay or Should I Go", "Rock"),
                new Song("A$AP Rocky", "L$D", "Hip-Hop"),
                new Song("Eric Church", "Talladega", "Country"),
                new Song("Anita Baker", "Caught Up in the Rapture", "R&B"),
                new Song("Flume", "Say It", "Electronic"),
                new Song("Sonny Rollins", "Oleo", "Jazz"),
                new Song("Maurice Ravel", "Pavane pour une infante défunte", "Classical"),
                new Song("Rihanna", "Only Girl (In The World)", "Pop"),
                new Song("Guns N' Roses", "November Rain", "Rock"),
                new Song("Tyler, the Creator", "See You Again", "Hip-Hop"),
                new Song("Faith Hill", "This Kiss", "Country"),
                new Song("Luther Vandross", "Dance with My Father", "R&B"),
                new Song("Justice", "We Are Your Friends", "Electronic"),
                new Song("Django Reinhardt", "Nuages", "Jazz"),
                new Song("Igor Stravinsky", "Petrushka", "Classical"),
                new Song("Selena Gomez", "Good for You", "Pop"),
                new Song("David Bowie", "Space Oddity", "Rock"),
                new Song("Meek Mill", "Going Bad", "Hip-Hop"),
                new Song("Trisha Yearwood", "How Do I Live", "Country"),
                new Song("Sam Cooke", "Bring It On Home to Me", "R&B"),
                new Song("Kygo", "Carry Me", "Electronic"),
                new Song("Art Blakey", "A Night in Tunisia", "Jazz"),
                new Song("Sergei Rachmaninoff", "Rhapsody on a Theme of Paganini", "Classical"),
                new Song("Ariana Grande", "Side to Side", "Pop"),
                new Song("Black Sabbath", "Iron Man", "Rock"),
                new Song("Lil Wayne", "Lollipop", "Hip-Hop"),
                new Song("Kenny Chesney", "She Thinks My Tractor's Sexy", "Country"),
                new Song("Marvin Gaye", "I Heard It Through the Grapevine", "R&B"),
                new Song("Major Lazer", "Cold Water", "Electronic"),
                new Song("Charlie Parker", "Scrapple from the Apple", "Jazz"),
                new Song("Johann Strauss II", "Voices of Spring", "Classical"),
                new Song("Ed Sheeran", "Thinking Out Loud", "Pop"),
                new Song("U2", "Sunday Bloody Sunday", "Rock"),
                new Song("J. Cole", "Love Yourz", "Hip-Hop"),
                new Song("Darius Rucker", "Alright", "Country"),
                new Song("Whitney Houston", "Saving All My Love for You", "R&B"),
                new Song("Alesso", "If I Lose Myself", "Electronic"),
                new Song("Herbie Hancock", "Chameleon", "Jazz"),
                new Song("Franz Liszt", "Liebestraum No. 3", "Classical"),
                new Song("Britney Spears", "Gimme More", "Pop"),
                new Song("Bruce Springsteen", "Dancing in the Dark", "Rock"),
                new Song("Travis Scott", "STARGAZING", "Hip-Hop"),
                new Song("Zac Brown Band", "Toes", "Country"),
                new Song("Otis Redding", "These Arms of Mine", "R&B"),
                new Song("deadmau5", "Some Chords", "Electronic"),
                new Song("Miles Davis", "Nardis", "Jazz"),
                new Song("Antonio Vivaldi", "Concerto for Strings in G Major", "Classical")
            };
            Artists = new List<Artist>
            {
                new Artist("Miles Davis"),
                new Artist("Ludwig van Beethoven"),
                new Artist("Taylor Swift"),
                new Artist("The Beatles"),
                new Artist("Kanye West"),
                new Artist("Johnny Cash"),
                new Artist("Stevie Wonder"),
                new Artist("Daft Punk"),
                new Artist("John Coltrane"),
                new Artist("Wolfgang Amadeus Mozart"),
                new Artist("Lady Gaga"),
                new Artist("Led Zeppelin"),
                new Artist("Tupac"),
                new Artist("Dolly Parton"),
                new Artist("Marvin Gaye"),
                new Artist("The Chemical Brothers"),
                new Artist("Duke Ellington"),
                new Artist("Frédéric Chopin"),
                new Artist("Britney Spears"),
                new Artist("The Rolling Stones"),
                new Artist("Notorious B.I.G."),
                new Artist("Garth Brooks"),
                new Artist("Michael Jackson"),
                new Artist("Calvin Harris"),
                new Artist("Billie Holiday"),
                new Artist("Antonio Vivaldi"),
                new Artist("Katy Perry"),
                new Artist("Pink Floyd"),
                new Artist("Jay-Z"),
                new Artist("Willie Nelson"),
                new Artist("Alicia Keys"),
                new Artist("Avicii"),
                new Artist("Charlie Parker"),
                new Artist("Johann Sebastian Bach"),
                new Artist("Ed Sheeran"),
                new Artist("Queen"),
                new Artist("Drake"),
                new Artist("Shania Twain"),
                new Artist("Whitney Houston"),
                new Artist("Tiesto"),
                new Artist("Louis Armstrong"),
                new Artist("Pyotr Ilyich Tchaikovsky"),
                new Artist("Camille Saint-Saëns"),
                new Artist("One Direction"),
                new Artist("Jimi Hendrix"),
                new Artist("Juice WRLD"),
                new Artist("Jason Aldean"),
                new Artist("Bobby Brown"),
                new Artist("Miles Davis"),
                new Artist("George Frideric Handel"),
                new Artist("Kesha"),
                new Artist("The Clash"),
                new Artist("A$AP Rocky"),
                new Artist("Eric Church"),
                new Artist("Anita Baker"),
                new Artist("Flume"),
                new Artist("Sonny Rollins"),
                new Artist("Maurice Ravel"),
                new Artist("Rihanna"),
                new Artist("Guns N' Roses"),
                new Artist("Tyler, the Creator"),
                new Artist("Faith Hill"),
                new Artist("Luther Vandross"),
                new Artist("Justice"),
                new Artist("Django Reinhardt"),
                new Artist("Igor Stravinsky"),
                new Artist("Selena Gomez"),
                new Artist("David Bowie"),
                new Artist("Meek Mill"),
                new Artist("Trisha Yearwood"),
                new Artist("Sam Cooke"),
                new Artist("Kygo"),
                new Artist("Art Blakey"),
                new Artist("Sergei Rachmaninoff"),
                new Artist("Ariana Grande"),
                new Artist("Black Sabbath"),
                new Artist("Lil Wayne"),
                new Artist("Kenny Chesney"),
                new Artist("Major Lazer"),
                new Artist("Charlie Parker"),
                new Artist("Johann Strauss II"),
                new Artist("U2"),
                new Artist("J. Cole"),
                new Artist("Darius Rucker"),
                new Artist("Whitney Houston"),
                new Artist("Alesso"),
                new Artist("Herbie Hancock"),
                new Artist("Franz Liszt"),
                new Artist("Britney Spears"),
                new Artist("Bruce Springsteen"),
                new Artist("Travis Scott"),
                new Artist("Zac Brown Band"),
                new Artist("Otis Redding"),
                new Artist("deadmau5"),
                new Artist("Miles Davis"),
                new Artist("Antonio Vivaldi"),
                new Artist("Lady Gaga"),
                new Artist("Pearl Jam"),
                new Artist("Drake"),
                new Artist("Dolly Parton"),
                new Artist("Erykah Badu"),
                new Artist("Zedd"),
                new Artist("John Coltrane"),
                new Artist("Johann Sebastian Bach"),
                new Artist("Taylor Swift"),
                new Artist("Led Zeppelin"),
                new Artist("JAY-Z"),
                new Artist("George Strait"),
                new Artist("Aretha Franklin"),
                new Artist("Calvin Harris"),
                new Artist("Ella Fitzgerald"),
                new Artist("Wolfgang Amadeus Mozart"),
                new Artist("Justin Bieber"),
                new Artist("The Rolling Stones"),
                new Artist("OutKast"),
                new Artist("Keith Urban"),
                new Artist("Tina Turner"),
                new Artist("Skrillex"),
                new Artist("Miles Davis"),
                new Artist("Frédéric Chopin"),
                new Artist("Katy Perry"),
                new Artist("AC/DC"),
                new Artist("Lil Nas X"),
                new Artist("Reba McEntire"),
                new Artist("Toni Braxton"),
                new Artist("Kygo"),
                new Artist("Billie Holiday"),
                new Artist("Ludwig van Beethoven"),
                new Artist("Adele"),
                new Artist("Queen"),
                new Artist("Eminem"),
                new Artist("Shania Twain"),
                new Artist("Sade"),
                new Artist("David Guetta"),
                new Artist("John Coltrane"),
                new Artist("Wolfgang Amadeus Mozart"),
                new Artist("Britney Spears"),
                new Artist("Metallica"),
                new Artist("Drake"),
                new Artist("Tim McGraw"),
                new Artist("Mariah Carey"),
                new Artist("Avicii"),
                new Artist("Miles Davis"),
                new Artist("Richard Strauss"),
                new Artist("Selena Gomez"),
                new Artist("The Who"),
                new Artist("Post Malone"),
                new Artist("Dierks Bentley"),
                new Artist("Beyoncé"),
                new Artist("Calvin Harris"),
                new Artist("Charlie Parker"),
                new Artist("Franz Schubert"),
                new Artist("Taylor Swift"),
                new Artist("The Beatles"),
                new Artist("Travis Scott"),
                new Artist("Garth Brooks"),
                new Artist("Alicia Keys"),
                new Artist("David Guetta"),
                new Artist("Herbie Hancock"),
                new Artist("Ludwig van Beethoven"),
                new Artist("Lady Gaga"),
                new Artist("Pink Floyd"),
                new Artist("Kendrick Lamar"),
                new Artist("Carrie Underwood"),
                new Artist("Usher"),
                new Artist("Marshmello"),
                new Artist("John Coltrane"),
                new Artist("Pyotr Ilyich Tchaikovsky"),
                new Artist("Ed Sheeran"),
                new Artist("The Rolling Stones"),
                new Artist("J. Cole"),
                new Artist("Luke Bryan"),
                new Artist("Marvin Gaye"),
                new Artist("Skrillex"),
                new Artist("Louis Armstrong"),
                new Artist("Frédéric Chopin"),
                new Artist("Justin Bieber"),
                new Artist("Led Zeppelin"),
                new Artist("Kanye West"),
                new Artist("Dolly Parton"),
                new Artist("Mary J. Blige"),
                new Artist("The Chainsmokers"),
                new Artist("Duke Ellington"),
                new Artist("Antonio Vivaldi"),
                new Artist("Billie Eilish"),
                new Artist("Nirvana"),
                new Artist("Eminem"),
                new Artist("Blake Shelton"),
                new Artist("Whitney Houston"),
                new Artist("Zedd"),
                new Artist("Duke Ellington"),
                new Artist("Johann Sebastian Bach"),
                new Artist("Ariana Grande"),
                new Artist("Linkin Park"),
                new Artist("Jay-Z"),
                new Artist("Brad Paisley"),
                new Artist("Janet Jackson"),
                new Artist("Tiesto"),
                new Artist("Stan Getz"),
                new Artist("Claude Debussy"),
                new Artist("Justin Timberlake"),
                new Artist("The Doors"),
                new Artist("Mac Miller"),
                new Artist("Shania Twain"),
                new Artist("Sade"),
                new Artist("Porter Robinson"),
                new Artist("Ella Fitzgerald"),
                new Artist("Camille Saint-Saëns"),
                new Artist("One Direction"),
                new Artist("Jimi Hendrix"),
                new Artist("Juice WRLD"),
                new Artist("Jason Aldean"),
                new Artist("Bobby Brown"),
                new Artist("Avicii"),
                new Artist("George Frideric Handel"),
                new Artist("Kesha"),
                new Artist("The Clash"),
                new Artist("A$AP Rocky"),
                new Artist("Eric Church"),
                new Artist("Anita Baker"),
                new Artist("Flume"),
                new Artist("Sonny Rollins"),
                new Artist("Maurice Ravel"),
                new Artist("Rihanna"),
                new Artist("Guns N' Roses"),
                new Artist("Tyler, the Creator"),
                new Artist("Faith Hill"),
                new Artist("Luther Vandross"),
                new Artist("Justice"),
                new Artist("Django Reinhardt"),
                new Artist("Igor Stravinsky"),
                new Artist("Selena Gomez"),
                new Artist("David Bowie"),
                new Artist("Meek Mill"),
                new Artist("Trisha Yearwood"),
                new Artist("Sam Cooke"),
                new Artist("Kygo"),
                new Artist("Art Blakey"),
                new Artist("Sergei Rachmaninoff"),
                new Artist("Ariana Grande"),
                new Artist("Black Sabbath"),
                new Artist("Lil Wayne"),
                new Artist("Kenny Chesney"),
                new Artist("Major Lazer"),
                new Artist("Charlie Parker"),
                new Artist("Johann Strauss II"),
                new Artist("Ed Sheeran"),
                new Artist("U2"),
                new Artist("J. Cole"),
                new Artist("Darius Rucker"),
                new Artist("Whitney Houston"),
                new Artist("Alesso"),
                new Artist("Herbie Hancock"),
                new Artist("Franz Liszt"),
                new Artist("Britney Spears"),
                new Artist("Bruce Springsteen"),
                new Artist("Travis Scott"),
                new Artist("Zac Brown Band"),
                new Artist("Otis Redding"),
                new Artist("deadmau5"),
                new Artist("Miles Davis"),
                new Artist("Antonio Vivaldi")
            };
            Account = new List<Accounts>();
            Genres = new List<Genre>
            {
                new Genre("Jazz"),
                new Genre("Classical"),
                new Genre("Pop"),
                new Genre("Rock"),
                new Genre("Hip-Hop"),
                new Genre("Country"),
                new Genre("R&B"),
                new Genre("Electronic")
            };
        }
        public Accounts SignIn(string email, string password)
        {
            return Account.FirstOrDefault(account => account.Email == email && account.Password == password);
        }
        public void SignOut()
        {
            CurrentUser = null;
        }
    }
}
